"""empty message

Revision ID: 60b47f788c53
Revises: None
Create Date: 2016-07-12 21:42:58.026539

"""

# revision identifiers, used by Alembic.
revision = '60b47f788c53'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Order_Time', sa.String(length=32), nullable=True),
    sa.Column('User', sa.String(length=32), nullable=True),
    sa.Column('Song', sa.String(length=64), nullable=True),
    sa.Column('Source', sa.String(length=128), nullable=True),
    sa.Column('Condition', sa.String(length=32), nullable=True),
    sa.Column('PS', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    ### end Alembic commands ###
